export default {
     regular: 'Nunito-Regular',
     medium: 'Nunito-Medium',
     bold: 'Nunito-Bold',
     light: 'Nunito-Light',
     thin: 'Nunito-Thin',
     semiBold: 'Nunito-SemiBold',
     extraBold: 'Nunito-ExtraBold',
     extraLight: 'Nunito-ExtraLight',
     black: 'Nunito-Black',
     italic: 'Nunito-Italic',
     popregular: 'Poppins-Regular',
     popmedium: 'Poppins-Medium',
     popbold: 'Poppins-Bold',
     poplight: 'Poppins-Light',
     popthin: 'Poppins-Thin',
     popsemiBold: 'Poppins-SemiBold',
     popextraBold: 'Poppins-ExtraBold',
     popextraLight: 'Poppins-ExtraLight',
     popblack: 'Poppins-Black',
     popitalic: 'Poppins-Italic',
   };